### ISSUE TITLE
Use editorconfig

### ISSUE THREAD

**Issue by rugk** [small-tech/should-i-pipe-it#9]
To prevent [these things](https://github.com/small-tech/should-i-pipe-it/pull/8/commits/74f7a49c3d08879b525b17529af2f204d686861e) maybe add an editorconfig file.

If you add an [editorconfig](http://editorconfig.org/) file you can easily make sure contributors choose the right indentation and similar things. They can choose from a variety of [editor plugins](http://editorconfig.org/#download) and it is even supported by GitHub by default.

**Comment by aral** [comment]
Good call, will look into it (and PRs welcome) ;)
